---
- name: VERIFY
  hosts: all
  become: true
  vars:
    ansible_ssh_common_args: " -F /tmp/ssh_config -o StrictHostKeyChecking=no"
  tasks:
    - name: PING
      ansible.builtin.ping:

    - name: Include author.template role
      ansible.builtin.include_role:
        name: author.template
      register: role_result

    - name: Verify role output
      ansible.builtin.assert:
        that:
          - "'Ansible Role Template' in (role_result.results | map(attribute='msg') | join(' '))"
